image:
  repository: kelvinsp/mlflow
  pullPolicy: Always
  tag: "latest"

strategy: RollingUpdate

restartPolicy: Always
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 5000
  targetPort: 5000

resources:
  limits:
    cpu: 800m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

dbConfig:
  host: "dorothy-mariadb.mlflow.svc.cluster.local"
  port: "3306"
  database: ""
  username: ""
  password: ""
  artifactRoot: "s3://datalake/mlflow/artifacts"
  #artifactRoot: "minio.mlflow.svc.cluster.local:9000"
