apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mlflow.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
spec:
  strategy:
    type: {{ .Values.strategy }}
  selector:
    matchLabels:
      {{- include "mlflow.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mlflow.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: {{ .Values.restartPolicy }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["bash", "-c", "mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri $BACKEND_STORE_URI --default-artifact-root $ARTIFACT_ROOT"]
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: HOST
              valueFrom:
                secretKeyRef:
                  name: {{ include "mlflow.fullname" . }}
                  key: host
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: {{ include "mlflow.fullname" . }}
                  key: port
            - name: DATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ include "mlflow.fullname" . }}
                  key: database
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "mlflow.fullname" . }}
                  key: username
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "mlflow.fullname" . }}
                  key: password
            - name: ARTIFACT_ROOT
              valueFrom:
                secretKeyRef:
                  name: {{ include "mlflow.fullname" . }}
                  key: artifactRoot
            - name: AWS_ACCESS_KEY_ID
              value: "access-key"
            - name: AWS_SECRET_ACCESS_KEY
              value: "secret-key"
            - name: MLFLOW_S3_ENDPOINT_URL
              value: "http://dorothy-minio.mlflow.svc.cluster.local:9000"
