apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mlflow.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
type: Opaque
data:
  host: {{ .Values.dbConfig.host | b64enc | quote }}
  port: {{ .Values.dbConfig.port | b64enc | quote }}
  username: {{ .Values.mariadb.auth.username | b64enc | quote }}
  password: {{ .Values.mariadb.auth.password | b64enc | quote }}
  database: {{ .Values.mariadb.auth.database | b64enc | quote }}
  artifactRoot: {{ .Values.dbConfig.artifactRoot | b64enc | quote }}
