apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mlflow.fullname" . }}
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
type: Opaque
data:
  backend-store-uri: {{ include "mlflow.backendStoreURI" . | quote }} {{/* # | b64enc | quote */}}
  access-key: {{ include "mlflow.artifactStore.accessKey" . | quote }} 
  secret-key: {{ include "mlflow.artifactStore.secretKey" . | quote }} 
