apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mlflow.fullname" . }}
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
type: Opaque
data:
  backend-store-uri: {{ include "mlflow.backendStoreURI" . | b64enc | quote }}
  access-key: {{ .Values.minio.accessKey.password | b64enc | quote }}
  secret-key: {{ .Values.minio.secretKey.password | b64enc | quote }}
