version: "3.7"
services:
  postgres:
    image: postgres:13.3
    restart: always
    environment:
      POSTGRES_DB: mlflow
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: supersafe
    ports:
      - 5432:5432
  #mysql:
  #  image: mysql:5.7
  #  command: --default-authentication-plugin=mysql_native_password
  #  restart: always
  #  ports:
  #    - 3306:3306
  #  expose:
  #    - 3306
  #  environment:
  #    MYSQL_ROOT_PASSWORD: root
  #    MYSQL_USER: admin
  #    MYSQL_PASSWORD: supersafe
  #    MYSQL_DATABASE: mlflow
  mlflow:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      #BACKEND_STORE_URI: mysql+pymysql://admin:supersafe@mysql:3306/mlflow
      BACKEND_STORE_URI: postgresql+psycopg2://admin:supersafe@postgres:5432/mlflow
      ARTIFACT_ROOT: /tmp
    ports:
      - 5000:5000
