version: "3.7"
services:
  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: supersafe
      MYSQL_DATABASE: mlflow
  dorothy:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      USER: admin
      PASS: supersafe
      HOST: mysql
      PORT: 3306
      DATABASE: mlflow
    ports:
      - 5000:5000
